### ISSUE TITLE
 I can't run it.

### ISSUE THREAD

**Issue by i-yavuz86** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31#13]
Hello . I do what is said but I can't get it to work. Is there a special button to operate it? In the manual it says local akm = 3, I write this, but what is this 3? Is it the 3 keys of the keyboard? Can you help me more clearly on how to do it? Please...

**Comment by i-yavuz86** [comment]
When I want to record
SYNTAX_ERROR Line Number:146

**Comment by i-yavuz86** [comment]
![Uploading error.jpg…]()

**Comment by i-yavuz86** [comment]
ll the code seems to be written on line 143 and does not work. Is there a corrected version? help please

**Comment by Nefarian91** [comment]
The macro does not react as it does not pull the mouse to the bottom

**Comment by Kava4** [comment]
Try the updated script.

**Comment by i-yavuz86** [comment]
thanks bro

**Comment by ibadik2005** [comment]
Brother, accept me in discord. He doesn't work for me.

**Comment by tu4nanh** [comment]
hello bro. Can you give me a link discord. help me something

**Comment by MrZETSU** [comment]
I PAY U PAYPAL IF U MAKE WORK FOR ME i trying but dont work
