### ISSUE TITLE
Variable for G512 keyboard 

### ISSUE THREAD

**Issue by rizki0309** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31#22]
hi, mouse (G502) key is working perfect, but i''m trying set on my G512 (LG HUB 2024.1) Keyboard with G Function ON (G light TURN ON), I try with key binding to 5 or F5 or G5 in your script its doesnt work...

what wrong with variable?

Thx You in advance

![308462546-817a9592-e45c-416a-b720-fa2056a2094a](https://github.com/Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-28/assets/161566614/f911a593-31f8-4a7d-a21b-16227ebd0e01)

**Comment by Kava4** [comment]
The working logic is the same as the Mouse. You have to change the "nil" value to a G button.
Example: local AK47_Keyboard = 3
For activate the AK47 we have to press G3.

**Comment by Kava4** [comment]
The working logic is the same as the Mouse. You have to change the "nil" value to a G button.
Example: local AKM_Keyboard = 3
For activate the AKM we have to press G3.
