### ISSUE TITLE
Problem with my G413 Loading  the script

### ISSUE THREAD

**Issue by shroudyw** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31#25]
Hello first of all thanks of the best script i ever used well the script works perfectly with my pro X superlight and cuz it got few buttons i wanted to use it with my G413 logitech keyboard but the script didnt work weirdly (G is on)

and again thanks for the script 

![Screenshot_13](https://github.com/Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-28/assets/165362926/ea43c878-a6c6-4871-8f01-74cc55bba5d6)
)

**Comment by shroudyw** [comment]
![image](https://github.com/Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-28/assets/165362926/39f75bcc-e7dd-4533-abb7-e25177b10b58)
![image](https://github.com/Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-28/assets/165362926/65bab605-57e7-4997-990d-850ce290527d)

**Comment by SrMilton** [comment]
@shroudyw did you find a solution? I have a G512 but I can't make G Keys works with G_PRESSED event.

**Comment by koakaiboy** [comment]
Can you adjust the macros recoil? I can't control it

**Comment by SrMilton** [comment]
@koakaiboy you need to fix the values by yourself. All new season some recoils changes and also the resolution you are using also changes the recoil multiplier

**Comment by koakaiboy** [comment]
> @koakaiboybạn cần tự sửa các giá trị. Tất cả các mùa mới đều có một số thay đổi về độ giật và độ phân giải bạn đang sử dụng cũng thay đổi hệ số nhân độ giật

Can you give me your macro and resolution reference?  i am using g203 mouse it works with macros but too powerful to control it
