### ISSUE TITLE
Adjusting recoil amount

### ISSUE THREAD

**Issue by geezlaweezuzz** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31#29]
Hello, I have used a few Logitech scripts in the past, but am new to trying this one out.  I like that you included the adjustments for things like 2x, 4x, as well as attachments/no attachments, etc. but I am having some problems.  I play on 1 vertical sensitivity multiplier in game, so I set the SensSetting to 1, which is explained in the guide.  However, the script is pulling down far too much, I am looking at the floor within 2 seconds of shooting.  Is it best that I just keep messing with (lowering) the SensSetting in order to get it to work decent, or is there other settings I should be adjusting?  Thanks!

**Comment by fabilied** [comment]
Hey, can you help me maybe to find the problem i have ? If i "activate" a no recoil weapon the script worked fine on the desktop but when i go ingame it doesnt work... yes i added the script in pubg and on desktop... and yes i tested it with only add the Script in pubg. Maybe any setting in pubg ? like the resolution or fullscreen mode ?

**Comment by koakaiboy** [comment]
Can you adjust the macros recoil? I can't control it

**Comment by szbm66666** [comment]
same problem here i tried to set the senssetting to 0.33 it works, but i have the same problem like u, have u figured out something?

**Comment by Kava4** [comment]
If the script works on desktop and not in game its because ghub is not opened as admin.
