### ISSUE TITLE
Update recoil table

### ISSUE THREAD

**Issue by thdung002** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31#31]
Since new update arrive today, AUG will decrease

> AUG
> Horizontal recoil decreased by approximately 2.3%.
> Vertical recoil decreased by approximately 4.5%.
> Recoil reduction while crouched increased from 13% → 14%.
> 
> MP5K
> The MP5K has been added to all maps.
> Available in Normal Match, Custom Match, and Ranked.
> Damage increased from 33 → 34.
> Horizontal recoil decreased by approximately 7%.
> Vertical recoil decreased by approximately 5%.
> Vertical recoil increases gradually.
> The reload time is reduced by approximately 15% when the bullet count reaches 0.
> 
> Tommy Gun
> Ammo: .45 ACP → 9mm
> Horizontal recoil decreased by approximately 5%.
> Vertical recoil decreased by approximately 7%.
> 
> UMP
> Ammo: .45 ACP → 9mm
> The weapon name has been changed from UMP45 → UMP to align with this change.
> Damage increased from 41 → 42.
> Horizontal recoil decreased by approximately 5%.
> 
> Micro UZI 
> Horizontal recoil decreased by approximately 10%.
> Vertical recoil decreased by approximately 15%.
> 
> PP-19 Bizon
> Damage increased from 36 → 38.
> Horizontal recoil decreased by approximately 5%.
> Vertical recoil decreased by approximately 5%.
> 
source https://pubg.com/en/news/7424

**Comment by Kava4** [comment]
I will post an update soon.

**Comment by thdung002** [comment]
Can u make like old script. Help to put line seperator in code to easy to adjust? inline code like now so hard to adjust

**Comment by Qiaoxi0** [comment]
I used it very well before.,Just found out that it's now updated with new gun data.,Can you share it?,Thank you, thank you.

**Comment by avielpa1** [comment]
any updates ?

**Comment by Kava4** [comment]
New script is ready.

**Comment by thdung002** [comment]
> New script is ready.

I just wonder if the sen of 2x 3x 4x 6x still remain like the pic in Game settings or just make all default?
