### ISSUE TITLE
Only load, but not working!

### ISSUE THREAD

**Issue by neliocaa** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31#32]
on change profile, when open the game, show on console LOADED, but keys not work,
already edit the keybind on file, but continue not working ingame, not work on desktop, not show logs on console
already open as admin

some tip?

**Comment by Lopper880** [comment]
local script_path = "your script file location"
local script = assert(loadfile(script_path))
script()
try this !

**Comment by neliocaa** [comment]
![image](https://github.com/Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-28/assets/4347596/5e3ab91a-1a04-4c07-83ee-2545ef62e936)

**Comment by Lopper880** [comment]
its G:\\meh.lua

**Comment by Lopper880** [comment]
\\  i mean

**Comment by Lopper880** [comment]
its `"G:\\meh.lua"`
