### ISSUE TITLE
mistake   SYNTAX_ERROR Line Number:194

### ISSUE THREAD

**Issue by denchik3025** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31#34]
I click save and run and the mistake error comes out 
 SYNTAX_ERROR Line Number:194

**Comment by erkan181** [comment]
Same

**Comment by emirygmr** [comment]
same error

**Comment by Kava4** [comment]
try the new script please

**Comment by Wargl1fad** [comment]
mistake SYNTAX_ERROR Line Number:193

**Comment by Ikhari** [comment]
still error

LOADED
SYNTAX_ERROR Line Number:193
SYNTAX_ERROR Line Number:193

**Comment by Kava4** [comment]
[See this](https://github.com/Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31/issues/39)
