### ISSUE TITLE
lua:192: ')' expected near '(' Line Number:1

### ISSUE THREAD

**Issue by dwbewiahn** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31#38]

**Comment by Kava4** [comment]
[See this](https://github.com/Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31/issues/39)

**Comment by dwbewiahn** [comment]
Now It's loading withou erros but I  am having some issues  with the config. I am following the steps. my sensitivity in game is 1.  so in the script local SensSetting = 1.  but in game  the aim go down like crazy. is there anything i am missing? It says general sens  and DPI doesnt matter. IDK what else can be the problem.  @Kava4

**Comment by dwbewiahn** [comment]
can you please delete this issue?
