### ISSUE TITLE
cant use it with my logitech keyboard

### ISSUE THREAD

**Issue by shroudyw** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-31#40]
can some1 help i cant  use the new script with my logitech keyboard G413
![image](https://github.com/user-attachments/assets/f9d66f1d-4daa-4cf9-a1b0-ce5046d4d405)

**Comment by Kava4** [comment]
You need to use the G keys on your keyboard not the F ones.

**Comment by shroudyw** [comment]
But the G keys are F1 F2… i dont know how to use it with the script

**Comment by Kava4** [comment]
Then replace the F1 with G1 for example.

**Comment by shroudyw** [comment]
![image](https://github.com/user-attachments/assets/f55e3791-d242-4050-a973-8bed717bf125)
![image](https://github.com/user-attachments/assets/f0f119f5-f436-414e-ab9f-273c850e14c9)
SAME :(

**Comment by Ikhari** [comment]
LoL, Your Keyboards doesn't have G-KEYS

![image](https://github.com/user-attachments/assets/8bba92ca-45c8-4b2d-a6ce-be36cea5f151)
